"""
Seed data for the Online Quiz App.
Each category maps to a list of tuples:
(question, option_a, option_b, option_c, option_d, correct_option)
"""

CATEGORIES = [
    "Python",
    "General Knowledge",
    "Mathematics",
    "Database",
    "Politics",
    "Indian Premier League",
]

QUESTIONS = {

    "Python": [
        ("What is the output of type([])?", "<class 'list'>", "<class 'tuple'>", "<class 'dict'>", "<class 'set'>", "A"),
        ("Which keyword is used to define a function in Python?", "func", "def", "function", "define", "B"),
        ("What does len('hello') return?", "4", "5", "6", "Error", "B"),
        ("Which of these is a mutable data type?", "tuple", "string", "list", "int", "C"),
        ("What is used to handle exceptions in Python?", "try/except", "catch/throw", "error/handle", "check/fix", "A"),
        ("Which operator is used for floor division?", "/", "//", "%", "**", "B"),
        ("What does 'pip' stand for?", "Python Install Package", "Pip Installs Packages", "Python Import Package", "Package Install Python", "B"),
        ("How do you start a comment in Python?", "//", "/*", "#", "--", "C"),
        ("What is the correct file extension for Python files?", ".py", ".pt", ".python", ".pyt", "A"),
        ("Which method converts a string to lowercase?", ".lower()", ".lowercase()", ".toLower()", ".down()", "A"),
        ("Which method converts a string to uppercase?", ".upper()", ".uppercase()", ".toUpper()", ".up()", "A"),
        ("Which built-in function returns the number of items in an object?", "size()", "count()", "len()", "length()", "C"),
        ("Which keyword is used to create a class in Python?", "class", "Class", "object", "struct", "A"),
        ("What is the correct syntax to create a list in Python?", "(1,2,3)", "[1,2,3]", "{1,2,3}", "<1,2,3>", "B"),
        ("What is the correct syntax to create a tuple in Python?", "[1,2,3]", "{1,2,3}", "(1,2,3)", "<1,2,3>", "C"),
        ("What is the correct syntax to create a dictionary in Python?", "[key:value]", "(key:value)", "{key:value}", "<key:value>", "C"),
        ("Which keyword is used for a conditional statement?", "when", "if", "check", "condition", "B"),
        ("Which keyword defines a loop that repeats while a condition is true?", "for", "while", "loop", "repeat", "B"),
        ("Which keyword is used to exit a loop early?", "stop", "break", "exit", "end", "B"),
        ("Which keyword skips the current loop iteration and continues to the next?", "skip", "continue", "next", "pass", "B"),
        ("What does the 'pass' statement do?", "Ends the program", "Does nothing (a placeholder)", "Skips a loop", "Raises an error", "B"),
        ("Which operator checks for equality in Python?", "=", "==", "===", "eq", "B"),
        ("Which operator is used for exponentiation in Python?", "^", "**", "pow", "exp", "B"),
        ("What is the output of 3 % 2?", "0", "1", "1.5", "2", "B"),
        ("Which data type represents True/False values?", "int", "bool", "str", "float", "B"),
        ("Which function converts a string to an integer?", "int()", "str()", "float()", "num()", "A"),
        ("Which function converts a number to a string?", "str()", "int()", "float()", "text()", "A"),
        ("What is a lambda function in Python?", "A named function", "An anonymous inline function", "A class method", "A loop construct", "B"),
        ("Which keyword is used to import a module?", "include", "import", "require", "using", "B"),
        ("What does the 'self' keyword refer to in a class method?", "The class itself", "The instance of the class", "A global variable", "The parent class", "B"),
        ("Which method is called automatically when an object is created?", "__init__()", "__new__()", "__start__()", "__create__()", "A"),
        ("Which keyword is used to handle code that always runs regardless of an exception?", "else", "finally", "except", "catch", "B"),
        ("Which keyword raises an exception manually?", "throw", "raise", "error", "except", "B"),
        ("What is a list comprehension used for?", "Creating a list in a concise way", "Deleting a list", "Copying a dictionary", "Sorting a tuple", "A"),
        ("Which method adds an item to the end of a list?", "append()", "add()", "insert()", "push()", "A"),
        ("Which method removes and returns the last item of a list?", "remove()", "pop()", "delete()", "discard()", "B"),
        ("Which method sorts a list in place?", "sort()", "sorted()", "order()", "arrange()", "A"),
        ("Which method returns a new sorted list without modifying the original?", "sort()", "sorted()", "order()", "arrange()", "B"),
        ("Which method reverses a list in place?", "reverse()", "flip()", "invert()", "swap()", "A"),
        ("Which keyword checks if a value exists in a sequence?", "has", "in", "contains", "exists", "B"),
        ("What does the 'is' operator check in Python?", "Value equality", "Identity (same object in memory)", "Type conversion", "Membership", "B"),
        ("Which data structure stores unique, unordered items with no duplicates?", "list", "tuple", "set", "dict", "C"),
        ("Which method returns the keys of a dictionary?", ".keys()", ".values()", ".items()", ".index()", "A"),
        ("Which method returns key-value pairs of a dictionary?", ".keys()", ".values()", ".items()", ".pairs()", "C"),
        ("What is the correct way to open a file for reading in Python?", "open('file','w')", "open('file','r')", "open('file','a')", "open('file','x')", "B"),
        ("Which statement ensures a file is properly closed after use?", "try/finally only", "with statement", "del statement", "close() manually only", "B"),
        ("Which module is commonly used for regular expressions in Python?", "regex", "re", "pattern", "match", "B"),
        ("Which built-in function returns the type of an object?", "type()", "typeof()", "kind()", "class()", "A"),
        ("What is the result of bool(0)?", "True", "False", "0", "Error", "B"),
        ("What is the result of bool(\"\")?", "True", "False", "Error", "None", "B"),
        ("Which keyword defines a function that can pause and resume, yielding values?", "return", "yield", "pause", "async", "B"),
        ("What is a generator in Python?", "A function that returns a list", "A function that yields values lazily", "A class decorator", "A type of loop", "B"),
        ("Which decorator is used to define a static method in a class?", "@staticmethod", "@classmethod", "@property", "@static", "A"),
        ("Which syntax is used to inherit from a parent class?", "extends Parent", "inherits Parent", "class Child(Parent):", "super Child", "C"),
        ("Which built-in function is used to call a parent class's method?", "parent()", "super()", "base()", "extend()", "B"),
        ("What is the purpose of the __name__ == \"__main__\" check?", "To import a module", "To check if the script is run directly", "To define a class", "To raise an exception", "B"),
        ("Which package manager is commonly used to install Python packages?", "npm", "pip", "gem", "cargo", "B"),
        ("Which of these is an immutable data type in Python?", "list", "dict", "set", "tuple", "D"),
    ],

    "General Knowledge": [
        ("What is the capital of France?", "London", "Berlin", "Paris", "Madrid", "C"),
        ("How many continents are there on Earth?", "5", "6", "7", "8", "C"),
        ("Who invented the telephone?", "Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Albert Einstein", "C"),
        ("Which planet is known as the Red Planet?", "Jupiter", "Venus", "Saturn", "Mars", "D"),
        ("What is the largest ocean on Earth?", "Atlantic", "Indian", "Arctic", "Pacific", "D"),
        ("How many days are in a leap year?", "365", "366", "364", "367", "B"),
        ("Which country is the largest by area?", "USA", "China", "Russia", "Canada", "C"),
        ("Who wrote 'Romeo and Juliet'?", "Charles Dickens", "William Shakespeare", "Mark Twain", "Homer", "B"),
        ("What is the largest continent by area?", "Africa", "Asia", "Europe", "North America", "B"),
        ("What is the smallest continent by area?", "Africa", "Australia", "Europe", "Antarctica", "B"),
        ("Which is the longest river in the world?", "Nile", "Amazon", "Yangtze", "Mississippi", "A"),
        ("Which is the tallest mountain in the world?", "K2", "Kangchenjunga", "Mount Everest", "Denali", "C"),
        ("Which is the largest hot desert in the world?", "Gobi", "Sahara", "Kalahari", "Thar", "B"),
        ("What is the capital of Japan?", "Osaka", "Kyoto", "Tokyo", "Yokohama", "C"),
        ("What is the capital of India?", "Mumbai", "New Delhi", "Kolkata", "Bengaluru", "B"),
        ("What is the capital of the United States?", "New York", "Los Angeles", "Washington, D.C.", "Chicago", "C"),
        ("What is the capital of the United Kingdom?", "Manchester", "London", "Birmingham", "Liverpool", "B"),
        ("What is the capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", "C"),
        ("What is the capital of Russia?", "St. Petersburg", "Moscow", "Kazan", "Novosibirsk", "B"),
        ("What is the capital of China?", "Shanghai", "Beijing", "Hong Kong", "Guangzhou", "B"),
        ("What is the capital of Egypt?", "Alexandria", "Cairo", "Giza", "Luxor", "B"),
        ("What is the currency of Japan?", "Won", "Yen", "Yuan", "Ringgit", "B"),
        ("What is the currency of India?", "Rupee", "Dollar", "Rial", "Dinar", "A"),
        ("What is the national language of France?", "French", "English", "Spanish", "German", "A"),
        ("Who painted the Mona Lisa?", "Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo", "C"),
        ("Who developed the theory of relativity?", "Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr", "B"),
        ("Who is known as the Father of the Nation in India?", "Jawaharlal Nehru", "Mahatma Gandhi", "Bhagat Singh", "Subhas Chandra Bose", "B"),
        ("Which gas do plants absorb from the atmosphere for photosynthesis?", "Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen", "B"),
        ("Which gas makes up most of Earth's atmosphere?", "Oxygen", "Carbon dioxide", "Nitrogen", "Argon", "C"),
        ("What is the chemical symbol for gold?", "Ag", "Au", "Gd", "Go", "B"),
        ("What is the chemical formula for water?", "H2O", "HO2", "O2H", "H3O", "A"),
        ("How many bones are there in the adult human body?", "196", "206", "216", "226", "B"),
        ("Which organ in the human body pumps blood?", "Lungs", "Liver", "Heart", "Kidney", "C"),
        ("Which is the largest mammal in the world?", "African elephant", "Blue whale", "Giraffe", "Polar bear", "B"),
        ("Which flightless bird is the fastest runner among birds?", "Penguin", "Ostrich", "Kiwi", "Emu", "B"),
        ("Which is the fastest land animal?", "Lion", "Cheetah", "Horse", "Leopard", "B"),
        ("In which year did World War II end?", "1943", "1945", "1947", "1950", "B"),
        ("In which year did World War I begin?", "1912", "1914", "1916", "1918", "B"),
        ("Who was the first person to walk on the Moon?", "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn", "B"),
        ("Which country is known as the Land of the Rising Sun?", "China", "Japan", "Thailand", "South Korea", "B"),
        ("Which ancient wonder was located in Giza, Egypt?", "Hanging Gardens", "Great Pyramid of Giza", "Colossus of Rhodes", "Lighthouse of Alexandria", "B"),
        ("Which is the smallest planet in our solar system?", "Mercury", "Mars", "Venus", "Pluto", "A"),
        ("Which is the largest planet in our solar system?", "Saturn", "Jupiter", "Neptune", "Uranus", "B"),
        ("What is the freezing point of water in Celsius?", "0°C", "32°C", "100°C", "-10°C", "A"),
        ("What is the boiling point of water in Celsius at sea level?", "90°C", "100°C", "110°C", "212°C", "B"),
        ("Which instrument is used to measure temperature?", "Barometer", "Thermometer", "Hygrometer", "Altimeter", "B"),
        ("Which instrument is used to measure atmospheric pressure?", "Thermometer", "Barometer", "Seismometer", "Anemometer", "B"),
        ("Who wrote the Indian national anthem 'Jana Gana Mana'?", "Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Sarojini Naidu", "Subhas Chandra Bose", "A"),
        ("Who wrote 'Vande Mataram'?", "Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Sarojini Naidu", "Jawaharlal Nehru", "B"),
        ("What is the national bird of India?", "Peacock", "Parrot", "Sparrow", "Crow", "A"),
        ("What is the national animal of India?", "Lion", "Tiger", "Elephant", "Leopard", "B"),
        ("What is the national flower of India?", "Rose", "Lotus", "Sunflower", "Marigold", "B"),
        ("Which is the longest river in India?", "Ganges", "Yamuna", "Godavari", "Brahmaputra", "A"),
        ("Which country has the largest population in the world (as of the 2020s)?", "China", "India", "USA", "Indonesia", "B"),
        ("Which is the smallest country in the world by area?", "Monaco", "Vatican City", "San Marino", "Liechtenstein", "B"),
        ("Which sea is the saltiest body of water on Earth?", "Red Sea", "Dead Sea", "Black Sea", "Caspian Sea", "B"),
        ("Which is the largest island in the world?", "Greenland", "Madagascar", "Borneo", "New Guinea", "A"),
        ("Which language has the most native speakers in the world?", "English", "Spanish", "Mandarin Chinese", "Hindi", "C"),
    ],

    "Mathematics": [
        ("What is the value of Pi (approx)?", "3.14", "2.17", "1.61", "3.41", "A"),
        ("What is 12 x 12?", "124", "136", "144", "148", "C"),
        ("What is the square root of 144?", "11", "12", "13", "14", "B"),
        ("What is 25% of 200?", "25", "40", "50", "75", "C"),
        ("Solve: 5! (5 factorial)", "60", "100", "120", "150", "C"),
        ("What is the sum of angles in a triangle?", "90°", "180°", "270°", "360°", "B"),
        ("What is 2 to the power of 10?", "512", "1024", "2048", "256", "B"),
        ("Which is a prime number?", "9", "15", "21", "17", "D"),
        ("What is 7 + 8?", "14", "15", "16", "17", "B"),
        ("What is 9 x 9?", "72", "81", "90", "99", "B"),
        ("What is 100 divided by 4?", "20", "25", "30", "40", "B"),
        ("What is the square of 9?", "18", "81", "90", "72", "B"),
        ("What is the cube of 3?", "6", "9", "27", "81", "C"),
        ("What is the value of 0! (zero factorial)?", "0", "1", "undefined", "-1", "B"),
        ("What is an even number?", "A number divisible by 2", "A number divisible by 3", "A prime number", "A negative number", "A"),
        ("What is an odd number?", "A number divisible by 2", "A number not divisible by 2", "A number divisible by 5", "Zero", "B"),
        ("What is the smallest prime number?", "0", "1", "2", "3", "C"),
        ("Is 1 considered a prime number?", "Yes", "No", "Sometimes", "Only in geometry", "B"),
        ("What is the sum of the first 5 natural numbers (1+2+3+4+5)?", "10", "15", "20", "25", "B"),
        ("What is the value of 10 squared?", "20", "100", "1000", "10", "B"),
        ("What is the square root of 81?", "8", "9", "10", "11", "B"),
        ("What is 3/4 expressed as a percentage?", "34%", "43%", "75%", "80%", "C"),
        ("What is 0.5 expressed as a fraction?", "1/2", "1/4", "1/5", "2/5", "A"),
        ("What is the LCM (Least Common Multiple) of 4 and 6?", "8", "12", "24", "4", "B"),
        ("What is the HCF/GCD of 12 and 18?", "3", "6", "9", "12", "B"),
        ("What is the perimeter of a square with side length 5?", "10", "15", "20", "25", "C"),
        ("What is the area of a square with side length 5?", "10", "15", "20", "25", "D"),
        ("What is the area of a rectangle with length 8 and width 3?", "11", "22", "24", "32", "C"),
        ("What is the circumference formula for a circle of radius r?", "πr", "2πr", "πr²", "2πr²", "B"),
        ("What is the area formula for a circle of radius r?", "πr", "2πr", "πr²", "2πr²", "C"),
        ("What is the sum of angles in a quadrilateral?", "180°", "270°", "360°", "450°", "C"),
        ("What is the value of x in 2x = 10?", "2", "5", "10", "20", "B"),
        ("What is the value of x in x + 7 = 15?", "6", "7", "8", "9", "C"),
        ("Solve for x: 3x - 4 = 11", "3", "4", "5", "6", "C"),
        ("What is the slope-intercept form of a line?", "y = mx + c", "y = x + m", "x = my + c", "y² = mx", "A"),
        ("The Pythagorean theorem is used to find what?", "The area of a circle", "The sides of a right triangle", "The volume of a cube", "Percentages", "B"),
        ("In a right triangle, what is the longest side called?", "Base", "Perpendicular", "Hypotenuse", "Altitude", "C"),
        ("What is the hypotenuse of a right triangle with legs 3 and 4?", "5", "6", "7", "8", "A"),
        ("What is the median of the numbers 3, 5, 7?", "3", "5", "7", "15", "B"),
        ("What is the mode of 2, 2, 3, 4, 5?", "2", "3", "4", "5", "A"),
        ("What is the mean of 2, 4, 6, 8?", "4", "5", "6", "8", "B"),
        ("What is a number's additive inverse?", "Its reciprocal", "The number that adds to it to make zero", "Its square", "Its cube", "B"),
        ("What is the reciprocal of 5?", "5", "-5", "1/5", "0", "C"),
        ("What does '%' represent in mathematics?", "Ratio", "Percentage", "Probability", "Fraction", "B"),
        ("What is 2 to the power of 5?", "10", "25", "32", "64", "C"),
        ("What is the value of 10 to the power of 0?", "0", "1", "10", "Undefined", "B"),
        ("What type of number cannot be expressed as a simple fraction, like π?", "Rational", "Irrational", "Whole", "Natural", "B"),
        ("What type of number includes 0, 1, 2, 3... with no negatives or fractions?", "Integers", "Whole numbers", "Rational numbers", "Real numbers", "B"),
        ("Which set of numbers includes negative numbers, zero, and positive numbers with no fractions?", "Whole numbers", "Natural numbers", "Integers", "Irrational numbers", "C"),
        ("What is the value of |-7| (absolute value)?", "-7", "7", "0", "14", "B"),
        ("What is the next number in the sequence 2, 4, 8, 16, ...?", "20", "24", "32", "36", "C"),
        ("What is the sum of the interior angles of a pentagon?", "360°", "450°", "540°", "720°", "C"),
        ("How many sides does a hexagon have?", "5", "6", "7", "8", "B"),
        ("How many sides does an octagon have?", "6", "7", "8", "9", "C"),
        ("What is the formula for the volume of a cube with side a?", "a²", "a³", "3a", "6a²", "B"),
        ("What is the formula for the volume of a cylinder with radius r and height h?", "πr²h", "2πrh", "πr²", "4/3πr³", "A"),
        ("What is the probability of flipping a coin and getting heads?", "0", "0.25", "0.5", "1", "C"),
        ("What is 15% of 300?", "30", "45", "60", "75", "B"),
    ],

    "Database": [
        ("What does SQL stand for?", "Structured Query Language", "Sequential Query Language", "Structured Question Language", "Server Query Language", "A"),
        ("Which command is used to fetch data from a database?", "UPDATE", "SELECT", "INSERT", "DELETE", "B"),
        ("Which SQL clause filters rows based on a condition?", "GROUP BY", "ORDER BY", "WHERE", "HAVING", "C"),
        ("Which keyword removes duplicate rows from a result set?", "UNIQUE", "DISTINCT", "ONLY", "FILTER", "B"),
        ("Which command adds new rows to a table?", "INSERT", "ADD", "CREATE", "APPEND", "A"),
        ("Which command modifies existing rows in a table?", "ALTER", "UPDATE", "MODIFY", "CHANGE", "B"),
        ("Which command deletes rows from a table?", "DROP", "REMOVE", "DELETE", "ERASE", "C"),
        ("Which command permanently removes a table and its structure?", "DELETE", "TRUNCATE", "DROP", "CLEAR", "C"),
        ("Which constraint ensures a column cannot have duplicate values?", "PRIMARY KEY", "UNIQUE", "CHECK", "DEFAULT", "B"),
        ("Which key uniquely identifies each record in a table?", "Foreign key", "Candidate key", "Primary key", "Composite key", "C"),
        ("Which key is used to link two tables together?", "Primary key", "Foreign key", "Super key", "Alternate key", "B"),
        ("Which SQL clause sorts the result set?", "GROUP BY", "ORDER BY", "SORT BY", "ARRANGE BY", "B"),
        ("Which SQL clause groups rows sharing a property?", "ORDER BY", "WHERE", "GROUP BY", "HAVING", "C"),
        ("Which clause filters groups after aggregation?", "WHERE", "HAVING", "GROUP BY", "FILTER", "B"),
        ("Which JOIN returns rows with matching values in both tables?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL JOIN", "C"),
        ("Which JOIN returns all rows from the left table and matched rows from the right?", "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN", "A"),
        ("Which JOIN returns all rows from both tables, matched or not?", "INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "RIGHT JOIN", "C"),
        ("Which SQL function counts rows?", "SUM()", "COUNT()", "TOTAL()", "ADD()", "B"),
        ("Which SQL function returns the average value?", "AVG()", "MEAN()", "SUM()", "MID()", "A"),
        ("Which SQL function returns the largest value?", "MAX()", "TOP()", "HIGH()", "BIG()", "A"),
        ("Which SQL function returns the smallest value?", "MIN()", "LOW()", "BOTTOM()", "SMALL()", "A"),
        ("Which command creates a new table?", "NEW TABLE", "CREATE TABLE", "MAKE TABLE", "ADD TABLE", "B"),
        ("Which command changes a table's structure?", "UPDATE TABLE", "MODIFY TABLE", "ALTER TABLE", "CHANGE TABLE", "C"),
        ("What does DDL stand for?", "Data Definition Language", "Data Deletion Language", "Database Design Language", "Data Display Language", "A"),
        ("What does DML stand for?", "Data Manipulation Language", "Data Management Language", "Database Modeling Language", "Data Migration Language", "A"),
        ("Which of these is a DML command?", "CREATE", "INSERT", "ALTER", "DROP", "B"),
        ("Which of these is a DDL command?", "SELECT", "UPDATE", "ALTER", "INSERT", "C"),
        ("What does DCL stand for?", "Data Control Language", "Data Command Language", "Database Control Language", "Data Constraint Language", "A"),
        ("Which command grants access privileges?", "GRANT", "ALLOW", "PERMIT", "ACCESS", "A"),
        ("Which command revokes access privileges?", "DENY", "REVOKE", "REMOVE", "BLOCK", "B"),
        ("What is normalization used for?", "Speeding up queries", "Reducing data redundancy", "Encrypting data", "Backing up data", "B"),
        ("What is the first normal form (1NF) primarily concerned with?", "Removing partial dependency", "Atomic column values", "Removing transitive dependency", "Removing all keys", "B"),
        ("What is a primary key made of two or more columns called?", "Foreign key", "Composite key", "Super key", "Alternate key", "B"),
        ("What is an index used for in a database?", "Encrypting rows", "Speeding up data retrieval", "Storing backups", "Grouping tables", "B"),
        ("What is a view in SQL?", "A physical table", "A virtual table based on a query", "A stored procedure", "A type of index", "B"),
        ("What is a stored procedure?", "A saved SQL query that can be executed", "A table backup", "A type of index", "A database user", "A"),
        ("What is a trigger in a database?", "A scheduled backup", "Code that runs automatically on an event", "A type of join", "A user permission", "B"),
        ("What does ACID stand for in transactions?", "Atomicity, Consistency, Isolation, Durability", "Accuracy, Consistency, Integrity, Durability", "Atomicity, Concurrency, Isolation, Durability", "Accuracy, Concurrency, Integrity, Data", "A"),
        ("Which statement ensures a set of operations succeed or fail together?", "INDEX", "TRANSACTION", "VIEW", "TRIGGER", "B"),
        ("Which command saves transaction changes permanently?", "COMMIT", "SAVE", "ROLLBACK", "UPDATE", "A"),
        ("Which command undoes changes made in a transaction?", "COMMIT", "UNDO", "ROLLBACK", "CANCEL", "C"),
        ("What is a foreign key constraint used for?", "Enforcing referential integrity", "Sorting data", "Encrypting data", "Indexing columns", "A"),
        ("Which SQL wildcard matches any sequence of characters in LIKE?", "?", "#", "%", "&", "C"),
        ("Which SQL wildcard matches a single character in LIKE?", "%", "_", "*", "?", "B"),
        ("What is the default sort order of ORDER BY?", "Descending", "Random", "Ascending", "Undefined", "C"),
        ("Which clause limits the number of rows returned in PostgreSQL?", "TOP", "LIMIT", "ROWNUM", "FETCH FIRST", "B"),
        ("What is a NULL value in SQL?", "Zero", "Empty string", "Unknown or missing value", "False", "C"),
        ("Which operator checks for NULL values?", "= NULL", "IS NULL", "== NULL", "EQUALS NULL", "B"),
        ("What type of database is MySQL?", "NoSQL", "Relational", "Graph", "Document", "B"),
        ("What type of database is MongoDB?", "Relational", "Document-based NoSQL", "Graph", "Key-value only", "B"),
        ("What does ERD stand for?", "Entity Relationship Diagram", "Entity Record Data", "Element Relation Design", "Entity Reference Document", "A"),
        ("In an ER diagram, what represents a real-world object?", "Attribute", "Entity", "Relationship", "Key", "B"),
        ("In an ER diagram, what describes a property of an entity?", "Entity", "Attribute", "Relationship", "Domain", "B"),
        ("What is a relationship where one record relates to many called?", "One-to-one", "One-to-many", "Many-to-many", "Self-referencing", "B"),
        ("What is a relationship where many records in one table relate to many in another called?", "One-to-one", "One-to-many", "Many-to-many", "Zero-to-one", "C"),
        ("What does 2NF (Second Normal Form) primarily eliminate?", "Repeating groups", "Partial dependency", "Transitive dependency", "Multivalued dependency", "B"),
        ("What does 3NF (Third Normal Form) primarily eliminate?", "Partial dependency", "Transitive dependency", "Repeating groups", "Composite keys", "B"),
        ("What is BCNF?", "A stricter version of 3NF", "A type of join", "A type of index", "A backup method", "A"),
        ("What is denormalization used for?", "Reducing redundancy", "Improving read performance by adding some redundancy", "Encrypting data", "Enforcing constraints", "B"),
        ("What does OLTP stand for?", "Online Transaction Processing", "Online Table Processing", "Offline Transaction Protocol", "Online Type Processing", "A"),
        ("What does OLAP stand for?", "Online Analytical Processing", "Offline Analytical Protocol", "Online Application Processing", "Online Aggregation Process", "A"),
        ("Which system is typically used for day-to-day transactional operations?", "OLTP", "OLAP", "ETL", "CAP", "A"),
        ("Which system is typically used for complex analytical queries and reporting?", "OLTP", "OLAP", "CRUD", "ACID", "B"),
        ("What is a data warehouse primarily used for?", "Real-time transactions", "Storing and analyzing large historical data", "Storing binary files only", "User authentication", "B"),
        ("What does ETL stand for?", "Extract, Transform, Load", "Execute, Test, Launch", "Extract, Test, Load", "Enter, Transfer, Load", "A"),
        ("What is sharding in databases?", "Splitting data horizontally across multiple servers", "Splitting data by column", "Encrypting rows", "Merging tables", "A"),
        ("What is database replication?", "Copying data across multiple servers for redundancy", "Deleting duplicate rows", "Compressing data", "Splitting a table into columns", "A"),
        ("What does the CAP theorem state a distributed system can guarantee at most two of?", "Consistency, Availability, Partition tolerance", "Concurrency, Atomicity, Persistence", "Cost, Accuracy, Performance", "Capacity, Availability, Performance", "A"),
        ("What does BASE stand for in NoSQL systems?", "Basically Available, Soft state, Eventually consistent", "Basic Atomicity Storage Engine", "Backup And Storage Engine", "Balanced Availability System Engine", "A"),
        ("Which of these is a NoSQL document database?", "MongoDB", "MySQL", "PostgreSQL", "Oracle", "A"),
        ("Which of these is a NoSQL key-value store?", "Redis", "MySQL", "SQLite", "PostgreSQL", "A"),
        ("Which of these is a NoSQL column-family database?", "Cassandra", "MongoDB", "Redis", "Neo4j", "A"),
        ("Which of these is a graph database?", "Neo4j", "MySQL", "MongoDB", "Redis", "A"),
        ("What is a composite index?", "An index on a single column", "An index on multiple columns", "An encrypted index", "A temporary index", "B"),
        ("What is a clustered index?", "An index that determines the physical order of data in a table", "An index stored separately from data", "An index only on primary keys", "A type of foreign key", "A"),
        ("What is a non-clustered index?", "An index that determines physical row order", "A separate structure pointing to the data rows", "A type of primary key", "A backup index", "B"),
        ("What is a subquery?", "A query nested inside another query", "A query that runs twice", "A backup query", "A query without a WHERE clause", "A"),
        ("What does UNION do in SQL?", "Combines rows from two queries, removing duplicates", "Combines columns from two tables", "Joins two tables on a key", "Filters duplicate rows only", "A"),
        ("What does UNION ALL do differently from UNION?", "Removes duplicates", "Keeps all rows including duplicates", "Sorts the result", "Groups the result", "B"),
        ("What is a self join?", "A table joined with itself", "A join with no conditions", "A join between two databases", "An automatic join", "A"),
        ("What is a CROSS JOIN?", "A join that returns the Cartesian product of two tables", "A join that filters null values", "A join that always returns one row", "A join between primary keys only", "A"),
        ("What does the COALESCE() function do?", "Returns the first non-null value from a list", "Combines two strings", "Counts rows", "Converts data types", "A"),
        ("What is a window function used for?", "Deleting rows", "Calculations across related rows without collapsing them", "Creating a new table", "Locking a table", "B"),
        ("What is a CHECK constraint used for?", "Enforcing a condition on column values", "Creating an index", "Encrypting a column", "Renaming a table", "A"),
        ("What does a NOT NULL constraint enforce?", "A column must always be unique", "A column cannot contain missing values", "A column must be numeric", "A column must be indexed", "B"),
        ("What does a DEFAULT constraint do?", "Sets a fallback value when none is provided", "Deletes the column", "Renames the column", "Locks the row", "A"),
        ("What does ON DELETE CASCADE do for a foreign key?", "Prevents deletion of the parent row", "Automatically deletes related child rows when the parent is deleted", "Archives deleted rows", "Blocks all deletes", "B"),
        ("What is a cursor in SQL used for?", "Iterating row-by-row through a result set", "Drawing UI elements", "Indexing a table", "Encrypting data", "A"),
        ("What is a key difference between a stored procedure and a function in SQL?", "A function must return a value; a procedure may not", "They are identical", "A procedure always returns a table", "A function cannot accept parameters", "A"),
        ("What is connection pooling used for?", "Reusing database connections to reduce overhead", "Encrypting connections", "Backing up a database", "Sharding data", "A"),
        ("Which isolation level prevents dirty reads but allows non-repeatable reads?", "Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable", "B"),
        ("Which isolation level offers the strictest consistency guarantee?", "Read Uncommitted", "Read Committed", "Repeatable Read", "Serializable", "D"),
        ("What is a 'dirty read'?", "Reading uncommitted data from another transaction", "Reading corrupted data", "Reading encrypted data", "Reading deleted data", "A"),
        ("What is a 'deadlock' in a database?", "Two transactions waiting on each other's locks indefinitely", "A crashed server", "A missing index", "A corrupted table", "A"),
        ("What is SQL injection?", "A method to speed up queries", "A vulnerability where malicious SQL is inserted into input fields", "A type of join", "A backup technique", "B"),
        ("What is the best practice to prevent SQL injection?", "Using parameterized queries/prepared statements", "Using SELECT * always", "Disabling indexes", "Using more joins", "A"),
        ("What is an ORM (Object-Relational Mapping)?", "A tool that maps database tables to objects in code", "A type of database index", "A backup format", "A query optimizer", "A"),
        ("Which of these is a popular Python ORM?", "SQLAlchemy", "NumPy", "Pandas", "Matplotlib", "A"),
        ("What is a database schema?", "The logical structure/blueprint of a database", "A backup file", "A type of index", "A stored procedure", "A"),
        ("What is the purpose of the EXPLAIN command in SQL?", "To describe how a query will be executed (query plan)", "To document a table", "To delete a table", "To encrypt a query", "A"),
    ],

    "Politics": [
        ("What is the term for a government where power is held by the people through elected representatives?", "Monarchy", "Democracy", "Autocracy", "Theocracy", "B"),
        ("What is a country ruled by a king or queen called?", "Republic", "Monarchy", "Democracy", "Oligarchy", "B"),
        ("What is a government controlled by a small group of powerful people called?", "Democracy", "Oligarchy", "Anarchy", "Federation", "B"),
        ("What term describes a state with no government or ruling authority?", "Anarchy", "Democracy", "Monarchy", "Theocracy", "A"),
        ("What is a government based on religious law called?", "Theocracy", "Democracy", "Monarchy", "Republic", "A"),
        ("What is the head of government in a parliamentary system usually called?", "President", "Prime Minister", "Governor", "Chancellor only", "B"),
        ("In a presidential system, who is typically both head of state and head of government?", "Prime Minister", "President", "Speaker", "Chief Justice", "B"),
        ("What is the legislative branch of government primarily responsible for?", "Enforcing laws", "Interpreting laws", "Making laws", "Collecting taxes", "C"),
        ("What is the judicial branch of government primarily responsible for?", "Making laws", "Interpreting laws", "Enforcing laws", "Managing elections", "B"),
        ("What is the executive branch primarily responsible for?", "Interpreting laws", "Making laws", "Enforcing/implementing laws", "Amending the constitution", "C"),
        ("What term describes the separation of government power into branches?", "Federalism", "Separation of powers", "Bicameralism", "Suffrage", "B"),
        ("What is a system with two legislative houses called?", "Unicameral", "Bicameral", "Tricameral", "Multicameral", "B"),
        ("What is a system with a single legislative house called?", "Bicameral", "Unicameral", "Federal", "Confederal", "B"),
        ("What is the right to vote called?", "Suffrage", "Ballot", "Quorum", "Mandate", "A"),
        ("What is a document outlining the fundamental laws of a nation called?", "Manifesto", "Constitution", "Treaty", "Statute", "B"),
        ("What term describes power divided between a central government and states?", "Unitary system", "Federal system", "Confederacy", "Monarchy", "B"),
        ("What term describes a system where most power rests with a central government?", "Federal system", "Unitary system", "Federation", "Confederation", "B"),
        ("What is a political party's statement of goals called?", "Constitution", "Manifesto", "Ballot", "Referendum", "B"),
        ("What is a direct vote by citizens on a specific issue called?", "Election", "Referendum", "Census", "Filibuster", "B"),
        ("What is the process of dividing a country into voting districts called?", "Census", "Redistricting", "Filibuster", "Ratification", "B"),
        ("What is a tactic of prolonged speech used to delay a legislative vote called?", "Veto", "Filibuster", "Quorum", "Coalition", "B"),
        ("What is the minimum number of members needed for a valid legislative vote called?", "Majority", "Quorum", "Plurality", "Consensus", "B"),
        ("What is the power of a head of state to reject a bill called?", "Amendment", "Veto", "Mandate", "Sanction", "B"),
        ("What is an alliance of political parties formed to run a government called?", "Coalition", "Filibuster", "Caucus", "Referendum", "A"),
        ("What is the term for winning with the most votes, even without a majority?", "Majority", "Plurality", "Quorum", "Unanimity", "B"),
        ("What is the practice of drawing electoral boundaries to favor one party called?", "Redistricting", "Gerrymandering", "Lobbying", "Campaigning", "B"),
        ("What is a group that seeks to influence legislation on behalf of an interest called?", "Coalition", "Lobby", "Caucus", "Cabinet", "B"),
        ("What is a country's group of senior ministers who advise the head of government usually called?", "Cabinet", "Congress", "Senate", "Tribunal", "A"),
        ("What is the supreme law-interpreting body of a country usually called?", "Parliament", "Supreme Court", "Cabinet", "Electoral Commission", "B"),
        ("Who was the first Prime Minister of India?", "Indira Gandhi", "Jawaharlal Nehru", "Lal Bahadur Shastri", "Sardar Patel", "B"),
        ("Who was the first President of India?", "Rajendra Prasad", "Zakir Husain", "S. Radhakrishnan", "V.V. Giri", "A"),
        ("In which year did India's Constitution come into effect?", "1947", "1950", "1952", "1949", "B"),
        ("What is the lower house of India's Parliament called?", "Rajya Sabha", "Lok Sabha", "Vidhan Sabha", "Vidhan Parishad", "B"),
        ("What is the upper house of India's Parliament called?", "Lok Sabha", "Rajya Sabha", "Vidhan Sabha", "Gram Sabha", "B"),
        ("What is the term length for a member of the US House of Representatives?", "2 years", "4 years", "6 years", "8 years", "A"),
        ("What is the term length for a US Senator?", "2 years", "4 years", "6 years", "8 years", "C"),
        ("What is the term length of a US President?", "2 years", "4 years", "6 years", "8 years", "B"),
        ("Which civilization is considered the birthplace of modern democracy?", "Rome", "Egypt", "Ancient Greece", "Persia", "C"),
        ("What is the term for a citizen's right to run for public office?", "Suffrage", "Eligibility", "Candidacy", "Ratification", "C"),
        ("A political system that legally allows only one party to hold power is called what?", "Multi-party system", "One-party system", "Two-party system", "Coalition system", "B"),
        ("What term describes an election system where one dominant party realistically wins every time?", "Swing state", "One-party dominant system", "Hung parliament", "Bipartisanship", "B"),
        ("What is a parliament where no single party has an outright majority called?", "Coalition government", "Hung parliament", "Minority veto", "Split senate", "B"),
        ("What is the ideology favoring minimal government intervention in the economy called?", "Socialism", "Laissez-faire liberalism", "Communism", "Theocracy", "B"),
        ("What is the ideology advocating collective or state ownership of production called?", "Capitalism", "Socialism", "Federalism", "Monarchism", "B"),
        ("What is a peaceful transfer of power through elections called?", "Coup d'état", "Democratic transition", "Revolution", "Annexation", "B"),
        ("What is an illegal, often sudden seizure of political power called?", "Referendum", "Coup d'état", "Impeachment", "Ratification", "B"),
        ("What is the formal legislative process of removing an official from office called?", "Recall", "Impeachment", "Veto", "Filibuster", "B"),
        ("What is the process by which citizens vote to remove an elected official before their term ends called?", "Impeachment", "Recall election", "Referendum", "Filibuster", "B"),
        ("What term describes a government policy applying equally to all citizens regardless of status?", "Rule of law", "Martial law", "Autocracy", "Federalism", "A"),
        ("What is the branch of political science that studies relations between nations called?", "Comparative politics", "International relations", "Public administration", "Political theory", "B"),
        ("What does UN stand for?", "United Nations", "United Nationalities", "Union of Nations", "United Neutral States", "A"),
        ("In which year was the United Nations founded?", "1919", "1945", "1950", "1960", "B"),
        ("How many permanent members does the UN Security Council have?", "3", "5", "7", "10", "B"),
        ("Which of these is NOT a permanent member of the UN Security Council?", "USA", "Russia", "Germany", "China", "C"),
        ("What does NATO stand for?", "North Atlantic Treaty Organization", "National Alliance Treaty Organization", "North American Trade Organization", "New Atlantic Trade Organization", "A"),
        ("What does WHO stand for?", "World Health Organization", "World Humanitarian Office", "Western Health Organization", "World Hospital Organization", "A"),
        ("What does IMF stand for?", "International Monetary Fund", "International Ministry of Finance", "Indian Monetary Fund", "International Market Federation", "A"),
        ("What does WTO stand for?", "World Trade Organization", "World Tariff Organization", "World Treaty Organization", "Western Trade Office", "A"),
        ("What does EU stand for?", "European Union", "Eastern Union", "Euro Union", "European Unity", "A"),
        ("What is the ICJ (International Court of Justice) primarily responsible for?", "Settling disputes between states", "Enforcing trade tariffs", "Managing global health", "Printing currency", "A"),
        ("Which 1215 document is considered a foundation of constitutional government in England?", "The Bill of Rights", "Magna Carta", "The Petition of Right", "The Act of Settlement", "B"),
        ("Which document declared the United States' independence from Britain in 1776?", "The Constitution", "The Bill of Rights", "The Declaration of Independence", "The Federalist Papers", "C"),
        ("The Universal Declaration of Human Rights is associated with which body?", "The League of Nations", "The United Nations", "NATO", "The European Union", "B"),
        ("In which year was the Universal Declaration of Human Rights adopted?", "1945", "1948", "1950", "1955", "B"),
        ("What voting system awards a seat to the candidate with the most votes in a constituency, regardless of majority?", "Proportional representation", "First-past-the-post", "Ranked-choice voting", "Mixed-member", "B"),
        ("What voting system allocates seats based on each party's share of votes?", "First-past-the-post", "Proportional representation", "Plurality voting", "Instant-runoff", "B"),
        ("What is a 'whip' in a political party?", "A punishment for MPs", "A party official who ensures members vote along party lines", "A ceremonial officer", "A campaign manager", "B"),
        ("What is the term for members of parliament who are not in the cabinet or shadow cabinet?", "Whips", "Backbenchers", "Frontbenchers", "Speakers", "B"),
        ("What is the role of the 'Leader of the Opposition' in a parliamentary system?", "Head of the ruling party", "Leader of the largest non-government party", "Head of the judiciary", "Chief of the civil service", "B"),
        ("What is an 'ombudsman'?", "An official who investigates public complaints against government bodies", "A type of judge", "A head of state", "A political party leader", "A"),
        ("Which ideology emphasizes individual liberty, free markets, and limited government?", "Conservatism", "Liberalism", "Fascism", "Communism", "B"),
        ("Which ideology emphasizes tradition, established institutions, and gradual change?", "Liberalism", "Conservatism", "Anarchism", "Socialism", "B"),
        ("Which ideology advocates the abolition of all government and hierarchical authority?", "Socialism", "Anarchism", "Fascism", "Federalism", "B"),
        ("Which ideology is characterized by extreme nationalism, dictatorship, and suppression of opposition?", "Liberalism", "Fascism", "Anarchism", "Federalism", "B"),
        ("What is 'nationalism'?", "Devotion to international cooperation", "Strong identification with and devotion to one's own nation", "A form of monarchy", "A judicial system", "B"),
        ("What is a 'welfare state'?", "A state focused only on military power", "A state that provides social services and economic security to citizens", "A state with no elections", "A one-party state", "B"),
        ("What is the term for a government's power to tax and spend?", "Fiscal policy", "Monetary policy", "Foreign policy", "Judicial policy", "A"),
        ("What is the term for a central bank's control over money supply and interest rates?", "Fiscal policy", "Monetary policy", "Trade policy", "Diplomatic policy", "B"),
        ("What is 'diplomacy'?", "The practice of conducting negotiations between nations", "Domestic law enforcement", "Military strategy", "Tax collection", "A"),
        ("What is a 'treaty'?", "A formal agreement between two or more states", "An internal party rule", "A court ruling", "A national holiday", "A"),
        ("What is 'sovereignty'?", "A nation's foreign debt", "Supreme authority of a state over its own territory and governance", "A type of election", "A trade agreement", "B"),
        ("What are 'sanctions' in international politics?", "Rewards given to allies", "Punitive economic or political measures against a country", "Peace treaties", "Military alliances", "B"),
        ("Who is the ceremonial Head of State in India?", "The Prime Minister", "The President", "The Chief Justice", "The Speaker", "B"),
        ("Who is the Head of Government in India?", "The President", "The Prime Minister", "The Vice President", "The Governor", "B"),
        ("What is the term length of the President of India?", "4 years", "5 years", "6 years", "7 years", "B"),
        ("Who holds the second-highest constitutional office in India after the President?", "Prime Minister", "Vice President", "Chief Justice", "Speaker", "B"),
        ("Which body in India is responsible for conducting free and fair elections?", "Supreme Court", "Election Commission of India", "Parliament", "Cabinet", "B"),
        ("What is the three-tier system of local self-governance in rural India called?", "Municipal Corporation", "Panchayati Raj", "Zila Parishad only", "Gram Sabha only", "B"),
        ("What is the head of a village-level Panchayat called?", "Sarpanch", "Mayor", "Collector", "Governor", "A"),
        ("What is the term for a state's chief executive head in India's federal system (elected)?", "Governor", "Chief Minister", "President", "Speaker", "B"),
        ("Who appoints the Governor of an Indian state?", "The Prime Minister", "The President", "The Chief Minister", "The Parliament", "B"),
        ("What is a 'hung assembly'?", "An assembly with a clear majority", "A state assembly where no party has a clear majority", "A dissolved assembly", "A ceremonial assembly", "B"),
        ("What is the term for the process by which an amendment or treaty formally becomes valid?", "Ratification", "Filibuster", "Gerrymandering", "Suffrage", "A"),
        ("The US Congress, made up of the House and Senate, is an example of what kind of legislature?", "Bicameral", "Unicameral", "Tricameral", "Confederal", "A"),
        ("What is the 'Electoral College' in the US primarily used for?", "Electing senators", "Electing the President", "Electing the Speaker", "Electing judges", "B"),
        ("What is a 'referendum' typically used to decide?", "A single specific policy or constitutional question put directly to voters", "The winner of a general election", "Judicial appointments", "Party leadership only", "A"),
        ("What is a 'plebiscite'?", "Another term for a direct popular vote on an issue", "A parliamentary session", "A cabinet meeting", "A court hearing", "A"),
        ("What is the term for citizens organizing to demand political or social change?", "Advocacy/activism", "Filibustering", "Gerrymandering", "Ratification", "A"),
        ("What term describes government actions and policies concerning relations with other countries?", "Domestic policy", "Foreign policy", "Fiscal policy", "Judicial policy", "B"),
        ("What is the term for a system where citizens vote directly on laws rather than through representatives?", "Representative democracy", "Direct democracy", "Theocracy", "Oligarchy", "B"),
    ],

    "Indian Premier League": [
        ("In which year was the first IPL season held?", "2007", "2008", "2009", "2010", "B"),
        ("Which team won the inaugural IPL season in 2008?", "Chennai Super Kings", "Rajasthan Royals", "Mumbai Indians", "Deccan Chargers", "B"),
        ("How many teams competed in the first IPL season?", "6", "8", "10", "12", "B"),
        ("Who captained Rajasthan Royals to their title win in the 2008 season?", "Rahul Dravid", "Shane Warne", "Shane Watson", "Graeme Smith", "B"),
        ("Which format of cricket does the IPL use?", "Test", "One Day (ODI)", "Twenty20 (T20)", "The Hundred", "C"),
        ("How many overs per innings are played in a standard IPL match?", "15", "20", "25", "50", "B"),
        ("Which city are the Mumbai Indians based in?", "Delhi", "Mumbai", "Pune", "Chennai", "B"),
        ("Which franchise is owned by Reliance Industries?", "Chennai Super Kings", "Mumbai Indians", "Kolkata Knight Riders", "Delhi Capitals", "B"),
        ("Which franchise is co-owned by actor Shah Rukh Khan?", "Punjab Kings", "Kolkata Knight Riders", "Sunrisers Hyderabad", "Royal Challengers Bengaluru", "B"),
        ("In which Indian city are the Chennai Super Kings based?", "Chennai", "Bengaluru", "Hyderabad", "Chandigarh", "A"),
        ("Which franchise did MS Dhoni captain for most of his IPL career?", "Rising Pune Supergiant", "Chennai Super Kings", "Mumbai Indians", "Delhi Daredevils", "B"),
        ("Which team is based in Bengaluru?", "Kings XI Punjab", "Royal Challengers Bengaluru", "Sunrisers Hyderabad", "Deccan Chargers", "B"),
        ("What was the earlier name of the Delhi Capitals franchise?", "Delhi Daredevils", "Delhi Dynamos", "Delhi Dashers", "Delhi Dragons", "A"),
        ("What was the earlier name of the Punjab Kings franchise?", "Punjab Panthers", "Kings XI Punjab", "Punjab Royals", "Mohali Kings", "B"),
        ("Which franchise later became Sunrisers Hyderabad after being disbanded?", "Deccan Chargers", "Kochi Tuskers Kerala", "Pune Warriors", "Gujarat Lions", "A"),
        ("In which year were Chennai Super Kings and Rajasthan Royals suspended from the IPL for two seasons?", "2013", "2014", "2016", "2018", "C"),
        ("Which two new franchises played during CSK and RR's suspension?", "Gujarat Lions and Rising Pune Supergiant", "Kochi Tuskers and Pune Warriors", "Deccan Chargers and Kochi Tuskers", "Lucknow and Ahmedabad", "A"),
        ("Which player has been a long-serving captain and icon player for Mumbai Indians?", "Rohit Sharma", "Virat Kohli", "MS Dhoni", "Suresh Raina", "A"),
        ("Which player is closely associated with Royal Challengers Bengaluru as a long-serving captain?", "Virat Kohli", "Rohit Sharma", "MS Dhoni", "David Warner", "A"),
        ("What is the toss-winning captain's first decision typically about?", "Choosing the umpire", "Choosing to bat or field first", "Choosing the pitch", "Choosing the venue", "B"),
        ("How many players are there in a cricket team on the field during a match?", "9", "10", "11", "12", "C"),
        ("What term describes a batter scoring 100 or more runs in an innings?", "Half-century", "Century", "Duck", "Hat-trick", "B"),
        ("What term describes a bowler taking three wickets on three consecutive deliveries?", "Maiden over", "Hat-trick", "Golden duck", "Century", "B"),
        ("What is it called when a batter is out for zero runs?", "Golden duck / duck", "Century", "Maiden", "Yorker", "A"),
        ("What is an over with no runs scored off the bat called?", "Golden over", "Maiden over", "Silent over", "Duck over", "B"),
        ("What is the fielding position directly behind the batter called?", "Slip", "Wicketkeeper", "Mid-on", "Point", "B"),
        ("What term is used when a limited-overs match ends without a result due to rain?", "Draw", "Washout / no result", "Tie", "Forfeit", "B"),
        ("Which method is used to adjust targets in rain-affected limited-overs matches?", "DRS", "DLS (Duckworth-Lewis-Stern) method", "VAR", "Super Over rule", "B"),
        ("What decides the winner if scores are tied at the end of an IPL match?", "A coin toss", "Super Over", "Replay of the match", "Shared trophy", "B"),
        ("What is the term for a delivery bowled at the batter's feet, hard to hit?", "Bouncer", "Yorker", "Full toss", "Googly", "B"),
        ("What is a fast, rising delivery aimed at the batter's head or chest called?", "Yorker", "Bouncer", "Full toss", "Doosra", "B"),
        ("What is a leg-spinner's delivery that turns the opposite way to expected called?", "Yorker", "Googly", "Bouncer", "Beamer", "B"),
        ("What award is given to the standout player of a single IPL match?", "Man of the Series", "Player of the Match", "Golden Bat", "Orange Cap", "B"),
        ("What is awarded to the leading run-scorer of an IPL season called?", "Purple Cap", "Orange Cap", "Golden Bat", "Gold Cap", "B"),
        ("What is awarded to the leading wicket-taker of an IPL season called?", "Orange Cap", "Purple Cap", "Silver Ball", "Golden Arm", "B"),
        ("In which IPL season was the 'Impact Player' substitution rule introduced?", "2022", "2023", "2024", "2021", "B"),
        ("What is the maximum number of overs a single bowler can bowl in an IPL innings?", "3", "4", "5", "6", "B"),
        ("How many balls are there in one standard cricket over?", "5", "6", "7", "8", "B"),
        ("What is it called when a delivery is bowled illegally down the leg or off side, out of the batter's reach?", "Wide", "Six", "Boundary", "Bye", "A"),
        ("What are extra runs called when they come off a wide delivery that the batter cannot play?", "Leg bye", "Wide", "No ball", "Bye", "B"),
        ("What are runs called when scored without the bat touching the ball, off the batter's body?", "Wide", "Bye", "Leg bye", "No ball", "C"),
        ("What is the fielding restriction limiting fielders outside the 30-yard circle called?", "Powerplay fielding restrictions", "Super Over rule", "DLS method", "Impact Player rule", "A"),
        ("How many powerplay overs are there at the start of an IPL innings?", "4", "6", "8", "10", "B"),
        ("What is the trophy awarded to the IPL champions each season called?", "The Ashes", "IPL Trophy", "World Cup", "Champions Cup", "B"),
        ("Which process is used to acquire new or uncontracted players before a season/cycle?", "Player draft only", "IPL player auction", "Direct signing", "Lottery pick", "B"),
        ("What is a player kept by their franchise without going into the auction called?", "Auctioned player", "Retained player", "Free agent", "Wildcard player", "B"),
        ("What is a player signed mid-season as a like-for-like replacement for an injured player called?", "Loan player", "Replacement player", "Impact substitute", "Reserve captain", "B"),
        ("What determines a team's ranking on the points table during the league stage?", "Net run rate only", "Points from wins, then net run rate", "Coin toss results", "Total boundaries hit", "B"),
        ("What does 'DRS' stand for in cricket?", "Direct Run System", "Decision Review System", "Delivery Rating System", "Dismissal Review Standard", "B"),
        ("In T20 cricket, how many runs are scored when the ball clears the boundary rope without bouncing?", "Four runs", "Six runs", "Out", "No run", "B"),
        ("Which organization governs the IPL?", "BCCI", "ICC", "ECB", "Cricket Australia", "A"),
        ("What does BCCI stand for?", "Board of Control for Cricket in India", "British Cricket Council of India", "Board of Cricket Control India", "Bureau of Cricket Control in India", "A"),
        ("Who is widely credited as the founder/architect of the IPL?", "Sourav Ganguly", "Lalit Modi", "N. Srinivasan", "Jagmohan Dalmiya", "B"),
        ("In which country is the IPL primarily hosted?", "Australia", "India", "England", "South Africa", "B"),
        ("In which year was the IPL held entirely in South Africa?", "2009", "2011", "2015", "2018", "A"),
        ("Where was the IPL 2020 season held due to the COVID-19 pandemic?", "India", "UAE", "Sri Lanka", "Bangladesh", "B"),
        ("What shape is a standard cricket field?", "Square only", "Oval/circular field", "Rectangular field", "Triangular field", "B"),
        ("What is the area at the center of a cricket ground called?", "The boundary", "The pitch", "The outfield", "The crease", "B"),
        ("How long is a standard cricket pitch, in yards?", "18 yards", "20 yards", "22 yards", "24 yards", "C"),
        ("What is the line a batter must stay behind to avoid being run out called?", "Boundary line", "Crease", "Pitch line", "Toss line", "B"),
        ("What is it called when a fielder catches the ball before it touches the ground to dismiss a batter?", "Run out", "Caught", "Stumped", "LBW", "B"),
        ("What does LBW stand for as a mode of dismissal?", "Leg Before Wicket", "Late Ball Warning", "Long Ball Wide", "Left Bat Wicket", "A"),
        ("What is it called when the wicketkeeper dismisses a batter who has stepped out of the crease?", "Run out", "Stumped", "Caught", "Hit wicket", "B"),
        ("What is it called when a batter's own bat or body dislodges the wicket?", "Stumped", "Run out", "Hit wicket", "Handled ball", "C"),
        ("What is it called when batters swap ends after running between the wickets?", "A run", "An over", "A boundary", "An extra", "A"),
        ("What is a 'boundary' in cricket?", "A run scored by hitting the ball to the edge of the field", "An out-of-bounds penalty", "A type of delivery", "A fielding position", "A"),
        ("How many runs are scored when the ball reaches the boundary after bouncing?", "Two", "Four", "Six", "Eight", "B"),
        ("What is a bowler's continuous spell of overs from one end called?", "Spell", "Session", "Innings", "Session break", "A"),
        ("What is the term for the team batting second, trying to reach the target set by the team batting first?", "Defending", "Chasing", "Setting", "Declaring", "B"),
        ("What does 'setting a target' mean?", "Batting second", "Batting first and setting a total to defend", "Winning the toss", "Bowling the last over", "B"),
        ("What is commonly the most crucial over bowled at the end of a T20 innings called?", "Powerplay over", "Death over", "Maiden over", "Opening over", "B"),
        ("What is a 'death bowler' known for?", "Bowling accurately in the final overs of an innings", "Opening the bowling", "Fielding at slip", "Batting at number 11", "A"),
        ("What is an all-rounder in cricket?", "A player skilled in both batting and bowling", "A player who only fields", "A team's captain", "A substitute player", "A"),
        ("What is a batter known for closing out innings under pressure commonly called?", "A bowler", "A finisher", "An umpire", "A team manager", "B"),
        ("What is the term for the batting order of a team?", "Line-up", "Squad", "Roster", "Panel", "A"),
        ("What is 'net run rate' used to determine?", "Individual batting average", "A team's overall scoring rate relative to opponents, used for tie-breaks", "Bowling economy only", "Strike rate", "B"),
        ("What is 'strike rate' in batting?", "Runs scored per 100 balls faced", "Runs scored per over", "Wickets taken per match", "Balls bowled per over", "A"),
        ("What is 'economy rate' in bowling?", "Runs conceded per over on average", "Wickets taken per match", "Balls bowled per innings", "Catches taken per match", "A"),
        ("What is a 'six' in cricket?", "The ball clearing the boundary after bouncing", "The ball clearing the boundary without bouncing", "Six balls in an over", "Six wickets down", "B"),
        ("Approximately how large is a full IPL squad including reserves, typically?", "5-10 players", "15-25 players", "30-40 players", "50-60 players", "B"),
        ("What is the term for a team's designated on-field leader?", "Captain", "Manager", "Coach", "Selector", "A"),
        ("What is the term for the person who trains and strategizes with the team off the field?", "Captain", "Head coach", "Umpire", "Match referee", "B"),
        ("What is the role of a 'match referee' in cricket?", "To bowl", "To oversee fair play and enforce the code of conduct", "To bat", "To select players", "B"),
        ("How many on-field umpires officiate a standard IPL match?", "1", "2", "3", "4", "B"),
        ("What additional official reviews decisions using technology in modern cricket?", "Third umpire", "Fourth umpire only", "Match referee", "Scorer", "A"),
        ("What is the area where players and support staff sit during a match called?", "Dugout", "Pavilion/dressing room", "Pit stop", "Bullpen", "B"),
        ("What is a 'toss' used to decide at the start of a match?", "The playing XI", "Who bats or bowls first", "The venue", "The umpire", "B"),
        ("What is a 'franchise' in the context of the IPL?", "A national cricket team", "A privately owned team representing a city/region in the league", "A stadium", "A sponsor", "B"),
        ("Which of these is an IPL franchise based in Rajasthan?", "Rajasthan Royals", "Punjab Kings", "Gujarat Titans", "Lucknow Super Giants", "A"),
        ("Which IPL team plays its home matches at Eden Gardens?", "Mumbai Indians", "Kolkata Knight Riders", "Chennai Super Kings", "Delhi Capitals", "B"),
        ("Which IPL team plays its home matches at the Wankhede Stadium?", "Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bengaluru", "Sunrisers Hyderabad", "B"),
        ("Which IPL team plays its home matches at the M. A. Chidambaram Stadium?", "Mumbai Indians", "Chennai Super Kings", "Kolkata Knight Riders", "Punjab Kings", "B"),
        ("Which two franchises joined the IPL starting from the 2022 season?", "Gujarat Titans and Lucknow Super Giants", "Kochi Tuskers and Pune Warriors", "Deccan Chargers and Rising Pune Supergiant", "Gujarat Lions and Rising Pune Supergiant", "A"),
        ("Which IPL team won the title in its debut season, 2022?", "Gujarat Titans", "Lucknow Super Giants", "Rajasthan Royals", "Punjab Kings", "A"),
        ("What does the IPL's salary cap / purse system primarily regulate?", "Ticket prices", "The total amount a franchise can spend on player acquisitions", "Sponsorship deals", "Stadium costs", "B"),
        ("What is a 'mega auction' in IPL terms?", "An auction held only for uncapped players", "A large auction, typically once every few years, where most players go unretained into the pool", "A charity auction", "An auction for stadium rights", "B"),
        ("What is the term for a player who has never played international cricket for their country?", "Capped player", "Uncapped player", "Retained player", "Overseas player", "B"),
        ("What is typically the maximum number of overseas players allowed in an IPL playing XI?", "2", "3", "4", "5", "C"),
        ("What is the term for a player from outside India who plays in the IPL?", "Domestic player", "Overseas/foreign player", "Reserve player", "Wildcard player", "B"),
        ("What is a 'right-hand bat' or 'left-hand bat' describing in cricket?", "The batter's height", "Which hand the batter leads with while batting", "The bowler's arm", "The fielding side", "B"),
    ],
}
